var http = require('http');
var fs = require('fs');
var url = require('url');
var axios = require('axios');
const { error } = require('console');


var preHTMLIndex = `
<!DOCTYPE html>
<html>
<style>
</style>
<body>
    <head>
        <title>Filmes</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="w3.css">
        <meta charset="utf-8"/>
    </head>
    <body>
`;

var postHTMLIndex = `
        <footer class="w3-container w3-theme-red">
            <h5>Generated by FilmesApp::EngWeb2024::a93323</h5>
        </footer>            
    </body>
</body>
</html> 
`

var pagInicial = preHTMLIndex +
`   
        <header class="w3-container w3-theme-red">
            <h3>Filmes</h3>
        </header>
        <div class="w3-container" style="max-width:500px;">
            <ul class="w3-ul w3-border w3-hoverable">
                <li><a href="/filmes">Filmes</a></li>
                <li><a href="/genero">Género</a></li>
                <li><a href="/atores">Atores</a></li>
            </ul>
        </div>
`
+ postHTMLIndex



function createFilmesIndex(dados){
    pagHTML = preHTMLIndex + 
    `
            <header class="w3-container w3-theme-red">
                <h3>Filmes</h3>
            </header>
            <div class="w3-container" style="max-width:500px;">
                <ul class="w3-ul w3-border w3-hoverable">
          
    `
    dados.forEach(elem => {
        pagHTML += `
                    <li><a href="/filmes/${elem.id}">${elem.title}</a></li>
        `
    });

    pagHTML += 
    `
                </ul>
            </div>
    `
    + postHTMLIndex
};

http.createServer(function (req,res){
    console.log(req.method + ' ' + req.url)
    var q = url.parse(req.url, true)
    console.log(q.pathname)
    if(q.pathname == '/w3.css'){
        fs.readFile('w3.css', function(erro, data){
            res.writeHead(200, {'Content-Type': 'text/css'})
            res.write(data)
            res.end()
        })
    }
    else if (q.pathname == '/'){
        res.writeHead(200, {'Content-Type': 'text/html; charset=utf-8'})
        res.write(pagInicial)
        res.end()
    }
    else if (q.pathname == '/filmes'){
        axios.get('http://localhost:3000/filmes')
        .then(function(response){
            dados = response.data
            pagHTML = createFilmesIndex(dados)
            res.writeHead(200, {'Content-Type': 'text/html; charset=utf-8'})
            res.write(pagHTML)
            res.end()
        })
        .catch(function(error){
            console.log(error)
        })
    }
    else{
        res.writeHead(400, {'Content-Type': 'text/html; charset=utf-8'})
        res.write('<p>Bad Request.</p>')
        res.end()
    }
}).listen(7777)